SaveMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path("", include("urls.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls/urls.py
from allauth.account.views import PasswordChangeView
from django.conf.urls import url
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views
from .models import Profile

urlpatterns = [
    path("", views.GamesView.as_view(), name ='game'),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<slug:slug>/", views.GamesDetailView.as_view(), name="game_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("publisher/<str:slug>/", views.PublisherView.as_view(), name="publisher_detail"),
    # url(r'^accounts/profile/$', ProfilePage.as_view(), name="profile"),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path("accounts/profile/", views.ProfileView.as_view(), name='profile'),
]

urls/models.py
from allauth.account.views import email
from django.core import mail
from django.core.mail import send_mail
from django.db import models

# Create your models here.
from django.db.backends import postgresql
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User
from faker.providers import address

from SaveMe.settings import EMAIL_HOST


class CommonInfo(models.Model):
    name = models.CharField("Название", max_length=50, db_index=True)

    class Meta:
        abstract = True



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    picture = models.ImageField("Картинка", upload_to="urls/", default='te2.jpg')
    # other fields...


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Categories(models.Model):
    """Категории гамесов"""
    name = models.CharField("Категория", max_length=50, db_index=True)
    description = models.TextField("Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Publisher(CommonInfo):
    name = models.CharField("Название", max_length=50, db_index=True)
    description = models.TextField("Описание")
    picture = models.ImageField("Картинка", upload_to="urls/")

    class Meta:
        verbose_name = "Издатель"
        verbose_name_plural = "Издатели"



class Games(CommonInfo):
    categories = models.ManyToManyField(Categories, verbose_name="категория")
    description = models.TextField("Описание")
    picture = models.ImageField("Картинка", upload_to="urls/")
    publisher = models.ManyToManyField(Publisher, verbose_name="издатель", related_name="creator")
    url = models.SlugField(max_length=160, unique=True)

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("game_detail", kwargs={"slug": self.url})


class Reviews(models.Model):
    name = models.CharField("Имя", max_length=50, db_index=True)
    text = models.TextField("Сообщение", max_length=50)
    picture = models.ImageField("Картинка", upload_to="urls/")
    game = models.ForeignKey(Games, verbose_name="игра", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.game}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class LostMail(object):

    def __init__(self):
        temp = models.CharField("Текст", max_length=400)
        send_mail.queue.put(temp)

    def __del__(self):
        send_mail(EMAIL_HOST, [address], False)


class MetaSingleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(MetaSingleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class DB(metaclass=MetaSingleton):
    connection = None

    def __init__(self):
        self.cursorobj = self.connection.cursor()

    def connect(self):
        if self.connection is None:
            self.connection = postgresql.connect("postgresql")
        return self.cursorobj

templates/games/game_detail.html
<!DOCTYPE html>
{% load static %}
{% load game_tag %}
<html lang="ru" xmlns:margin-left="http://www.w3.org/1999/xhtml">
<head>
    <!-- //Meta tag Keywords -->
    <title>BoardWorld</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>

<div id="page" class="page">
    <div class="main-banner inner bg bg1" id="home">
        <!-- header -->
        <header class="header">
            <div class="container-fluid px-lg-5">
                <!-- nav -->
                <nav class="py-4">
                    <div id="logo">
                        <h1><a href="/" class="editContent"
                               style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">BoardWorld</a>
                        </h1>
                    </div>

                    <ul class="menu mt-2">
                        <li class="active"><a href="/">Главная</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="/accounts/profile/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Профиль</a>
                            </li>
                            <li><a href="/accounts/logout/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Выход</a>
                            </li>
                        {% else %}
                            <li><a href="/accounts/login/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- //nav -->
            </div>
        </header>
    </div>
    <!--//main-content-->
    <!---->
    <ol class="breadcrumb editContent">
    </ol>
    <!---->
    <!-- banner -->
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(33, 37, 41); font-size: 16px; background-color: rgba(0, 0, 0, 0); font-family: Lato, sans-serif;">
        <div class="container py-md-3">
            <!-- top Products -->
            <div class="row">
                <!-- product left -->
                <div class="side-bar col-lg-4">

                    <div class="search-bar w3layouts-newsletter">
                        <h3 class="sear-head editContent">Поиск игры</h3>
                        <form action="{% url 'search' %}" method="get" class="d-flex editContent">
                            <input type="search" placeholder="Введите название..." name="q" class="form-control"
                                   required="">
                            <button type="submit" class="btn1 btn">
                                <span class="fa fa-search" aria-hidden="true"></span>
                            </button>
                        </form>
                    </div>
                    <!--preference -->
                    <div class="left-side my-4">
                        <h3 class="sear-head editContent">Категории</h3>
                        <ul class="w3layouts-box-list">
                            {% get_cat as cats %}
                            {% for categories in cats %}
                                {{ categories.name }}
                                <p class="editContent" style="outline: none; cursor: inherit;">
                                    {{ categories.description }}
                                </p>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- // preference -->
                    <!-- discounts -->
                    <!-- //discounts -->
                    <!-- reviews -->
                    <!-- //reviews -->
                    <!-- deals -->
                    <!-- //deals -->
                    <!-- //deals -->

                </div>
                <!-- //product left -->
                <!-- product right -->
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ game_list.picture.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="...">
                                {{ game_list.name }}
                            </h3>
                            <ul>
                                <li style="list-style: none"><span><b>Категория:</b>
                                    {% for cat in game_list.categories.all %}
                                        {{ cat.name }}
                                    {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>Издатель:</b>
                                    {% for publisher in game_list.publisher.all %}
                                        <a href="{% url 'publisher_detail' publisher.name %}">
                                        {{ publisher.name }}
                                        <a/>
                                    {% endfor %}
                                <li style="list-style: none">
                                    <p class="editContent" style="outline: none; cursor: inherit;">
                                        {{ game_list.description }}
                                    </p>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <p>
                            <img src="bundles/images/about.jpg" class="img-fluid" alt="">
                            <img src="bundles/images/admin.jpg" class="img-fluid" alt="">
                            <img src="bundles/images/d1.jpg" class="img-fluid" alt="">
                        </p>
                    </div>
                    <hr>
                    <div class="row">
                        {% if user.is_authenticated %}

                            <div class="single-form-left">
                                <!-- contact form grid -->
                                <div class="contact-single">
                                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                                        <span class="sub-tittle editContent"></span>
                                        Оставить отзыв
                                    </h3>
                                    <form action="{% url 'add_review' game_list.id %}" method="post" class="mt-4">
                                        {% csrf_token %}
                                        <div class="form-group editContent">
                                            <div class="d-sm-flex">
                                                <div class="col-sm-6 form-group p-0 editContent">
                                                    <input type="hidden" class="form-control border" value= "{{ user.username }}" name="name"
                                                           id="contactusername" required="">
                                                </div>
                                            </div>

                                            <label for="contactcomment" class="editContent">
                                                Ваш комментарий *
                                            </label>
                                            <textarea class="form-control border" rows="6" cols="70" name="text"
                                                      id="contactcomment" required=""></textarea>
                                        </div>
                                        <button type="submit"
                                                class="mt-3 btn btn-success btn-block py-3">
                                            Отправить
                                        </button>
                                    </form>
                                </div>
                                <!--  //contact form grid ends here -->
                            </div>
                        {% endif %}
                        {% for review in game_list.reviews_set.all %}
                            <div class="media py-5">
                                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image"
                                     style="outline: none; cursor: inherit; margin-right: 2000px">
                                <div class="media-body mt-4">
                                    <h5 class="mt-0 editContent"
                                        style="outline: none; cursor: inherit; margin-right: 1000px">
                                        {{ review.name }}
                                    </h5>
                                    <p class="mt-2 editContent"
                                       style="outline: none; cursor: inherit; margin-right: 100px; padding: 1px; white-space: pre-line;">
                                        {{ review.text }}

                                    </p>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
</body>

templates/games/games.html
<!DOCTYPE html>

{% load static %}
{% load game_tag %}


<html lang="ru">
<head>
    <title>BoardWorld</title>
    <!-- //Meta tag Keywords -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>

<div id="page" class="page"><!-- mian-content -->
    <div class="main-banner inner bg bg1" id="home">
        <!-- header -->
        <header class="header">
            <div class="container-fluid px-lg-5">
                <!-- nav -->
                <nav class="py-4">
                    <div id="logo">
                        <h1><a href="/" class="editContent"
                               style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">BoardWorld</a>
                        </h1>
                    </div>

                    <ul class="menu mt-2">
                        {% if user.is_authenticated %}
                            <li><a href="/accounts/profile/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Профиль</a>
                            </li>
                            <li><a href="/accounts/logout/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Выход</a>
                            </li>
                        {% else %}
                            <li><a href="/accounts/login/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- //nav -->
            </div>
        </header>
    </div>
    <!--//main-content-->
    <!---->
    <ol class="breadcrumb editContent">
    </ol>
    <!---->
    <!-- banner -->
    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
        <div class="container-fluid py-md-3">
            <div class="row">
                <div class="side-bar col-lg-3">

                    <div class="search-bar w3layouts-newsletter">
                        <h3 class="sear-head editContent">Поиск игры</h3>
                        <form action="{% url 'search' %}" method="get" class="d-flex editContent">
                            <input type="search" placeholder="Введите название..." name="q" class="form-control"
                                   required="">
                            <button type="submit" class="btn1 btn">
                                <span class="fa fa-search" aria-hidden="true"></span>
                            </button>
                        </form>
                    </div>
                    <!--preference -->
                    <div class="left-side my-4">
                        <h3 class="sear-head editContent">Категории</h3>
                        <ul class="w3layouts-box-list">
                            {% get_cat as cats %}
                            {% for categories in cats %}
                                {{ categories.name }}
                                <p class="editContent" style="outline: none; cursor: inherit;">
                                    {{ categories.description }}
                                </p>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- // preference -->
                    <!-- discounts -->
                    <!-- //discounts -->
                    <!-- reviews -->
                    <!-- //reviews -->
                    <!-- deals -->
                    <!-- //deals -->

                </div>
                <!-- //product left -->
                <!-- product right -->
                <div class="left-ads-display col-lg-9">
                    <div class="row">
                        {% for game in games_list %}
                            <div class="col-md-4 product-men">
                                <div class="product-shoe-info editContent text-center mt-lg-4">
                                    <div class="men-thumb-item">
                                        <img src="{{ game.picture.url }}" class="img-fluid" alt="">
                                    </div>
                                    <div class="item-info-product">
                                        <h4 class="">
                                            <a href="{{ game.get_absolute_url }}" class="editContent">
                                                {{ game.name }}
                                            </a>
                                        </h4>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <!--<div class="grid-img-right mt-4 text-right bg bg1" >
                        <span class="money editContent" >Flat 50% Off</span>
                        <a href="moviesingle.html" class="btn" >Now</a>
                    </div>-->
                </div>
            </div>
        </div>
    </section>
    <!-- //contact -->
    <!-- footer -->

    <!-- //footer -->

</div>
</body>
</html>

templates/games/publisher.html
<!DOCTYPE html>
{% load static %}
{% load game_tag %}
<html lang="ru" xmlns:margin-left="http://www.w3.org/1999/xhtml">
<head>
    <!-- //Meta tag Keywords -->
    <title>BoardWorld</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>

<div id="page" class="page">
    <div class="main-banner inner bg bg1" id="home">
        <!-- header -->
        <header class="header">
            <div class="container-fluid px-lg-5">
                <!-- nav -->
                <nav class="py-4">
                    <div id="logo">
                        <h1><a href="/" class="editContent"
                               style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">BoardWorld</a>
                        </h1>
                    </div>

                    <ul class="menu mt-2">
                        <li class="active"><a href="/">Главная</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="/accounts/profile/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Профиль</a>
                            </li>
                            <li><a href="/accounts/logout/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Выход</a>
                            </li>
                        {% else %}
                            <li><a href="/accounts/login/"
                                   style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- //nav -->
            </div>
        </header>
    </div>
    <!--//main-content-->
    <!---->
    <ol class="breadcrumb editContent">
        <li class="breadcrumb-item">
    </ol>
    <!---->
    <!-- banner -->
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(33, 37, 41); font-size: 16px; background-color: rgba(0, 0, 0, 0); font-family: Lato, sans-serif;">
        <div class="container py-md-3">
            <!-- top Products -->
            <div class="row">
                <!-- product left -->
                <div class="side-bar col-lg-4">

                        <div class="search-bar w3layouts-newsletter">
                        <h3 class="sear-head editContent">Поиск игры</h3>
                        <form action="{% url 'search' %}" method="get" class="d-flex editContent">
                            <input type="search" placeholder="Введите название..." name="q" class="form-control"
                                   required="">
                            <button type="submit" class="btn1 btn">
                                <span class="fa fa-search" aria-hidden="true"></span>
                            </button>
                        </form>
                    </div>
                    <!--preference -->
                    <div class="left-side my-4">
                        <h3 class="sear-head editContent">Категории</h3>
                        <ul class="w3layouts-box-list">
                            {% get_cat as cats %}
                            {% for categories in cats %}
                                {{ categories.name }}
                                <p class="editContent" style="outline: none; cursor: inherit;">
                                    {{ categories.description }}
                                </p>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
                <!-- //product left -->
                <!-- product right -->
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ publisher.picture.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="...">
                                {{ publisher.name }}
                            </h3>
                            <li style="list-style: none"><span><b>Игры:</b>
                                {% for game in publisher.creator.all %}
                                    {{ game.name }}
                                {% endfor %}
                                </span>
                            </li>
                            <li style="list-style: none">
                                <p class="editContent" style="outline: none; cursor: inherit;">
                                    {{ publisher.description }}
                                </p>

                            </li>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <p>
                            <img src="bundles/images/about.jpg" class="img-fluid" alt="">
                            <img src="bundles/images/admin.jpg" class="img-fluid" alt="">
                            <img src="bundles/images/d1.jpg" class="img-fluid" alt="">
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
</body>

templates/games/send_email.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block content %}
<form method="post" action="{% url 'email' %}">
    {% csrf_token %}
    <div>
        <div>
            <p>{{ form.users.errors }}</p>
            <p>{{ form.users.label_tag }}</p>
            <p>
                {% for user in form.users.initial %}
                    {{ user.email }}{% if not forloop.last %},&nbsp;{% endif %}
                {% endfor %}
            </p>
            <select name="users" multiple style="display: none">
                {% for user in form.users.initial %}
                    <option value="{{ user.id }}" selected>{{ user }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <p>{{ form.subject.errors }}</p>
            <p>{{ form.subject.label_tag }}</p>
            <p>{{ form.subject }}</p>
        </div>
        <div>
            <p>{{ form.message.errors }}</p>
            <p>{{ form.message.label_tag }}</p>
            <p>{{ form.message }}</p>
        </div>
        <input type="hidden" name="action" value="send_email"/>
        <input type="submit" name="send" value="{% trans 'Send message' %}"/>
    </div>
</form>
{% endblock %}